export const REQUEST_COUNTRY_STATS = 'REQUEST_COUNTRY_STATS'
export const COUNTRY_STATS_SUCCESS = 'COUNTRY_STATS_SUCCESS'
export const COUNTRY_STATS_FAILED = 'COUNTRY_STATS_FAILED'

export const SET_COUNTRY_USER_COUNT = 'SET_COUNTRY_USER_COUNT'
export const SET_COUNTRY_TOP_FOLLOWED_LIST = 'SET_COUNTRY_TOP_FOLLOWED_LIST'
